modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/SlimeKnights/Mantle/issues"
logoFile="Mantle.png"
license="MIT"

[[mods]]
    modId="mantle"
    version="${version}"
    displayName="Mantle"
    authors="Slime Knights"
    description='''
Shared code for Slime Knights mods and others.
    '''
    displayURL="https://minecraft.curseforge.com/projects/mantle"

[[dependencies.mantle]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mantle]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
